#!/usr/bin/env sh

set -eu

if [ ${SHOVE_DEBUG:-} ]; then
  set -x
fi

SHOVE_SHELL=${SHOVE_SHELL:-$SHELL}
SHOVE_TMPFILE=./.shaq.tmp.sh

target=$1

: > $SHOVE_TMPFILE
echo ". lib/t.shrc" >> $SHOVE_TMPFILE
echo "t_init" >> $SHOVE_TMPFILE
cat $target >> $SHOVE_TMPFILE
echo "t_report" >> $SHOVE_TMPFILE

if [ ${SHOVE_DEBUG:-} ]; then
  SHOVE_SHELL="$SHOVE_SHELL -x"
fi

echo "# $target by $SHOVE_SHELL"

set +e
$SHOVE_SHELL $SHOVE_TMPFILE
result=$?
set -e

rm -f $SHOVE_TMPFILE

exit $result
